### ISSUE TITLE
Abrir la opción para subir Pull Request

### ISSUE THREAD

**Issue by GonzaloAfa** [celiavelmar/open-covid19-test#3]
Para poder contribuir al código, podrías habilitar la opción para que otros podamos subir `branch` y hacer aportes mediante `Pull Request`.
En mi caso acabo de limpiar un poco el código de `/src/views/Test.vue` pero no lo puedo subir jejeje.

**Comment by UlisesGascon** [comment]
Hola @GonzaloAfa!

Creo que podrías hacerlo haciendo [un fork](https://help.github.com/en/github/getting-started-with-github/fork-a-repo) y luego mandando un [PR desde el propio fork](https://help.github.com/en/github/getting-started-with-github/fork-a-repo)

Si ya has trabajado tus cambios en una version clonada de este repo, puedes añadir el [fork como remote](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/configuring-a-remote-for-a-fork) y hacer un push con lo que tus cambios estarían en el fork.

De esta forma no tienes problemas de permisos ni nada 👍

**Comment by GonzaloAfa** [comment]
> Hola @GonzaloAfa!
> 
> Creo que podrías hacerlo haciendo [un fork](https://help.github.com/en/github/getting-started-with-github/fork-a-repo) y luego mandando un [PR desde el propio fork](https://help.github.com/en/github/getting-started-with-github/fork-a-repo)
> 
> Si ya has trabajado tus cambios en una version clonada de este repo, puedes añadir el [fork como remote](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/configuring-a-remote-for-a-fork) y hacer un push con lo que tus cambios estarían en el fork.
> 
> De esta forma no tienes problemas de permisos ni nada 👍

Gracias por las indicaciones! No tenia idea que así se podía aportar a los proyectos jejeje.
